version: '2'
services:
  web:
    image: buildkite/puppeteer:latest
    container_name: puppeteer_container
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: [sh, -c, npm install && npm start]
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"
